trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 9 * * *"
    displayName: Daily 9AM Run
    branches:
      include:
        - main
    always: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.10"
      addToPath: true

  - script: python -m pip install --upgrade pip
    displayName: "Upgrade pip"

  - script: pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: sudo apt-get update && sudo apt-get install -y curl
    displayName: "Install curl"

  - script: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    displayName: "Setup Node.js"

  - script: sudo apt-get install -y nodejs
    displayName: "Install Node.js"

  - script: npx playwright install-deps
    displayName: "Install Playwright dependencies"

  - script: rfbrowser init
    displayName: "Init Browser Library"

  - script: mkdir -p evidence/screenshots evidence/pdf
    displayName: "Prepare evidence folders"

  - script: robot -v Headless:true -v device:s1 ./src/test
    displayName: "Run Robot Framework tests"

  - script: |
      cp log.html evidence/
      cp report.html evidence/
      cp output.xml evidence/
    displayName: "Copy Robot logs to evidence folder"